apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.consumer.name }}
  namespace: {{ .Values.kafka.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.consumer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.consumer.name }}
    spec:
      containers:
      - name: {{ .Values.consumer.name }}
        image: {{ .Values.consumer.image.name }}: {{- .Values.consumer.image.tag }}
        imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}
        env:
          - name: BOOTSTRAP_SERVERS
            value: {{ .Values.kafka.bootstrap.server }}: {{- .Values.kafka.bootstrap.port }}
          - name: TOPIC
            value: {{ .Values.kafka.topic.name }}
          - name: GROUP_ID
            value: {{ .Values.consumer.GROUP_ID }}