apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: kafka
  labels:
    name: kafka-go-consumer
spec:
  scaleTargetRef:
    kind: Deployment
    name: kafka-go-consumer
  pollingInterval: 10
  minReplicaCount: 0
  maxReplicaCount: 5
  cooldownPeriod: 5
  triggers:
  - type: kafka
    metadata:
    #   bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      consumerGroup: my-kafka-go-consumer      # Make sure that this consumer group name is the same one as the one that is consuming topics
      topic: my-topic
      # Optional
      lagThreshold: "1"
      offsetResetPolicy: latest
    #   sasl: plaintext
    #   tls: enable
    # authenticationRef:
    #   name: keda-kafka-credentials