apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: {{ .Values.kafka.namespace }}
  labels:
    name: {{ .Values.consumer.name }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Values.consumer.name }}
  pollingInterval: 10
  minReplicaCount: 2
  maxReplicaCount: 5
  cooldownPeriod: 5
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: {{ .Values.kafka.bootstrap.server }}.kafka.svc.cluster.local: {{- .Values.kafka.bootstrap.port }}
      consumerGroup: {{ .Values.consumer.GROUP_ID }}
      topic: {{ .Values.kafka.topic.name }}
      lagThreshold: "1"
      offsetResetPolicy: latest