apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: {{ .Values.observability.namespace }}
spec:
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: prometheus-kube-prometheus-prometheus
  ports:
    - port: {{ .Values.observability.prometheus.port }}
      targetPort: {{ .Values.observability.prometheus.targetPort }}
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: {{ .Values.observability.namespace }}
spec:
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  ports:
    - port: {{ .Values.observability.grafana.port }}
      targetPort: {{ .Values.observability.grafana.targetPort }}
  type: LoadBalancer