apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: observability
spec:
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: prometheus-kube-prometheus-prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: observability
spec:
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer