apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-go-producer
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka-go-producer
  template:
    metadata:
      labels:
        app: kafka-go-producer
    spec:
      containers:
      - name: kafka-go-producer
        image: diwakar50/kafka-go-producer:latest
        imagePullSecrets:
          - name: regcred
        env:
          - name: BOOTSTRAP_SERVERS
            value: "my-cluster-kafka-bootstrap:9092"
          - name: TOPIC
            value: "my-topic"