apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.producer.name }}
  namespace: {{ .Values.kafka.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.producer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.producer.name }}
    spec:
      containers:
      - name: kafka-go-producer
        image: {{ .Values.producer.image.name }}: {{- .Values.producer.image.tag }}
        imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}
        env:
          - name: BOOTSTRAP_SERVERS
            value: {{ .Values.kafka.bootstrap.server }}: {{- .Values.kafka.bootstrap.port }}
          - name: TOPIC
            value: {{ .Values.kafka.topic.name }}